### ISSUE TITLE
绑定手上物品时出现的错误

### ISSUE THREAD

**Issue by China-Nshen** [SakuraTown/SakuraBind#12]
当global-setting,yml内的lore-index: -2这样设置，使用指令:/sab bindTo item id。会出现以下错误：[11:30:52] [Craft Scheduler Thread - 666/WARN]: [SakuraBind] Plugin SakuraBind v2.4.0 generated an exception while executing task 446558
java.lang.IndexOutOfBoundsException: Index: 44, Size: 42
        at java.util.ArrayList.rangeCheckForAdd(Unknown Source) ~[?:1.8.0_301]
        at java.util.ArrayList.addAll(Unknown Source) ~[?:1.8.0_301]
        at top.iseason.bukkit.sakurabind.SakuraBindAPI.updateLore$lambda$9(SakuraBindAPI.kt:365) ~[?:?]
        at top.iseason.bukkit.sakurabind.libs.core.utils.bukkit.ItemUtils.applyMeta(ItemUtils.kt:52) ~[?:?]
        at top.iseason.bukkit.sakurabind.SakuraBindAPI.updateLore(SakuraBindAPI.kt:338) ~[?:?]
        at top.iseason.bukkit.sakurabind.SakuraBindAPI.bind(SakuraBindAPI.kt:122) ~[?:?]
        at top.iseason.bukkit.sakurabind.SakuraBindAPI.bind(SakuraBindAPI.kt:69) ~[?:?]
        at top.iseason.bukkit.sakurabind.SakuraBindAPI.bind$default(SakuraBindAPI.kt:60) ~[?:?]
        at top.iseason.bukkit.sakurabind.command.BindToCommand.onExecute$lambda$2(BindToCommand.kt:42) ~[?:?]
        at top.iseason.bukkit.sakurabind.libs.core.command.CommandNode.onCommand$lambda$7(CommandNode.kt:232) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-5a600445]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-5a600445]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_301]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]

**Comment by Iseason2000** [comment]
已修复。可以先下载预览版本 https://github.com/SakuraTown/SakuraBind/actions/runs/11737446500/artifacts/2161718171
或者等待下个正式版本发布

由于消息过多可能会漏掉issue提醒邮件，如需获得实时问题反馈请加QQ群: 887296263

**Comment by Iseason2000** [comment]
已经2.4.3版本中解决
