### ISSUE TITLE
无法创建配置文件

### ISSUE THREAD

**Issue by zfms4188** [SakuraTown/SakuraBind#7]
`[02:33:45] [Server thread/ERROR]: Error occurred while disabling SakuraBind v2.2.11 (Is it up to date?)
java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.createListBuilder()Ljava/util/List;
        at top.iseason.bukkit.sakurabind.libs.core.config.SimpleYAMLConfig.<init>(SimpleYAMLConfig.kt:74) ~[?:?]
        at top.iseason.bukkit.sakurabind.libs.core.config.SimpleYAMLConfig.<init>(SimpleYAMLConfig.kt:26) ~[?:?]
        at top.iseason.bukkit.sakurabind.config.Config.<init>(Config.kt:24) ~[?:?]
        at top.iseason.bukkit.sakurabind.config.Config.<clinit>(Config.kt) ~[?:?]
        at top.iseason.bukkit.sakurabind.cache.CacheManager.<clinit>(CacheManager.kt:38) ~[?:?]
        at top.iseason.bukkit.sakurabind.SakuraBind.onDisable(SakuraBind.kt:206) ~[?:?]
        at top.iseason.bukkit.sakurabind.libs.core.BukkitTemplate.onDisable(BukkitTemplate.java:151) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[JavaPlugin.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:352) [JavaPluginLoader.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [SimplePluginManager.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [SimplePluginManager.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:405) [CraftServer.class:git-CatServer-1.12.2-090a6ffb]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:507) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:853) [?:1.8.0_292]`

测试环境
CatServer-090a6ffb-universal  核心
SakuraBind-2.2.11

**Comment by zfms4188** [comment]
经过二分法排除
测试出和mod冲突 
Shadowfacts' Forgelin-1.8.4  最新版
https://www.mcmod.cn/class/799.html
此mod也使用了kotlin语言

**Comment by Iseason2000** [comment]
使用替代品 https://github.com/MineCraftGensoukyo/Forgelin
